# Generated by Django 4.1.7 on 2023-02-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_bathroom_remove_property_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
    ]
