# Generated by Django 4.1.7 on 2023-02-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('dedicated_work_space', models.BooleanField(default=True)),
                ('pool', models.BooleanField(default=True)),
                ('ac', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=True)),
                ('TV', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=True)),
                ('view', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_per_night', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('property_type', models.PositiveIntegerField(choices=[(1, 'Hotel'), (2, 'Bungalow'), (3, 'Flat'), (4, 'PG')], default=1)),
                ('address', models.TextField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('review', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('date', models.DateField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
